title: Pendidikan Ekonomi UNIAS
description: Menjadi Program Studi Pendidikan Ekonomi yang unggul dan inovatif dalam menghasilkan pendidik ekonomi profesional, berkarakter, adaptif terhadap perkembangan zaman.
